version: 1
disable_existing_loggers: true
formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(message)s"
  simple:
    format: "[%(levelname)s] %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: geodatautils.log
    mode: w
loggers:
  root:
    level: DEBUG
    handlers: [console,file]