version: 1

solr instances:
  dev:
    url: "https://geodata-dev.shc.wisc.edu/solr/geodata-core/"
    username: "yourusername"
    password: "yourpassword"
  test:
    url: "https://geodata-test.sco.wisc.edu/solr/geodata-core/"
    username: "yourusername"
    password: "yourpassword"
  prod:
    url: "https://geodata.wisc.edu/solr/geodata-core/"
    username: "yourusername"
    password: "yourpassword"

error-checks:
  properties-not-null: ["dc_title_s", "dc_identifier_s", "layer_slug_s", "solr_geom", "dct_provenance_s", "dc_rights_s", "geoblacklight_version", "dc_creator_sm", "dc_description_s", "dct_references_s", "dct_temporal_sm", "solr_year_i", "layer_modified_dt"]
  identifier-layer-slug-match: true
  temporal-contains-solr-year: true
  title-contains-solr-year: true
  references-contains-solr-year: true
  existing-uid: true

log:
  version: 1
  disable_existing_loggers: true
  filters:
    indent:
      (): "geodatautils.logging_config.DefaultIndent"
  formatters:
    default:
      format: "%(asctime)s [%(levelname)s]%(indent)s%(label)s%(message)s"
    simple:
      format: "%(indent)s%(label)s%(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      filters: [indent]
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: default
      filters: [indent]
      filename: geodatautils.log
      mode: w
      encoding: utf8
  loggers:
    urllib3:
      handlers: [console]
      propagate: no
  root:
      level: INFO
      handlers: [console, file]

metadata-schema:
  options:
    geoblacklight-aardvark: geoblacklight-schema-aardvark.json
    geoblacklight-1: geoblacklight-schema-1.0.json
    geoblacklight-1-wisc: geoblacklight-schema-1.0-wisc.json
  default: geoblacklight-1-wisc