version: 1

solr instances:
  dev:
    url: "https://geodata-dev.shc.wisc.edu/solr/geodata-core/"
    username: "yourusername"
    password: "yourpassword"
  test:
    url: "https://geodata-test.sco.wisc.edu/solr/geodata-core/"
    username: "yourusername"
    password: "yourpassword"
  prod:
    url: "https://geodata.wisc.edu/solr/geodata-core/"
    username: "yourusername"
    password: "yourpassword"

log:
  version: 1
  disable_existing_loggers: true
  filters:
    indent:
      (): "geodatautils.logging_config.DefaultIndent"
  formatters:
    default:
      format: "%(asctime)s [%(levelname)s]%(indent)s%(message)s"
    simple:
      format: "%(indent)s%(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      filters: [indent]
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: default
      filters: [indent]
      filename: geodatautils.log
      mode: w
      encoding: utf8
  loggers:
    urllib3:
      handlers: [console]
      propagate: no
  root:
      level: INFO
      handlers: [console, file]

metadata-schemas:
  geoblacklight-aardvark: geoblacklight-schema-aardvark.json
  geoblacklight-1: geoblacklight-schema-1.0.json
  geoblacklight-1-no_enum: geoblacklight-schema-1.0-no_enum.json